const saved=JSON.parse(localStorage.getItem("nexus-progress")||"null");
const state=saved||{page:"dashboard",xp:0,solved:0,streak:0,done:false,courses:{}};
function levelFromXp(xp){return Math.floor(xp/1000)+1}
function save(){localStorage.setItem("nexus-progress",JSON.stringify({xp:state.xp,solved:state.solved,streak:state.streak,done:state.done,courses:state.courses}))}
const missions=[["The Stolen Server","Web • Hard","Find the compromised account in a fictional ACME incident."],["Packet Storm","Networking • Medium","Trace suspicious traffic and reconstruct the timeline."],["Ghost File","Forensics • Hard","Analyze evidence and recover the hidden artifact."]];
const courses=[
  ["🐧","Linux Foundations","7 lessons","Terminal basics, files, permissions and processes.","84%"],
  ["🌐","Networking","9 lessons","TCP/IP, DNS, HTTP, ports, routing and packet thinking.","61%"],
  ["🕸️","Web Security","12 lessons","HTTP, authentication, sessions, input validation and safe lab practice.","72%"],
  ["🐍","Python for Security","8 lessons","Automation, parsing, requests, logs and defensive tooling.","36%"],
  ["🔐","Cryptography","10 lessons","Hashes, encoding, symmetric crypto, public-key concepts and signatures.","12%"],
  ["🕵️","Digital Forensics","11 lessons","Evidence handling, metadata, logs, timelines and analysis.","18%"],
  ["🧬","Reverse Engineering","10 lessons","Binaries, strings, control flow and analysis workflows.","0%"],
  ["🛡️","Blue Team / SOC","9 lessons","Detection, triage, incident response and hardening.","0%"]
];
const labs=[["🛒","OWASP Juice Shop","Web • Beginner → Expert","http://127.0.0.1:3000"],["🐐","OWASP WebGoat","Web • Beginner → Advanced","http://127.0.0.1:8081/WebGoat/"],["💉","DVWA","Web • Beginner → Advanced","http://127.0.0.1:4280"]];
const external=[["Hack The Box","https://www.hackthebox.com/"],["PortSwigger Web Security Academy","https://portswigger.net/web-security"],["TryHackMe","https://tryhackme.com/"]];
const tools=[["🔎","Hash Analyzer"],["🧩","Codec Lab"],["📄","Metadata"],["📝","Log Analyzer"],["🔤","Hex Viewer"],["📊","JWT Decoder"]];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function cardButton(label,page,primary=false){return '<button class="btn '+(primary?"primary":"")+'" data-page="'+page+'">'+label+'</button>'}
function shell(){
 const nav=[["dashboard","⌂","Dashboard"],["learn","🎓","Learn"],["missions","🎯","Missions"],["labs","🧪","Real Labs"],["terminal","💻","Terminal"],["tools","🧰","Toolkit"],["ctf","🚩","CTF Arena"],["ai","🤖","Gemini AI"]];
 return '<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">N</div>NEXUS</div><nav>'+nav.map(x=>'<button class="nav-btn '+(state.page===x[0]?"active":"")+'" data-page="'+x[0]+'">'+x[1]+'&nbsp; '+x[2]+'</button>').join("")+'</nav><div class="footer-note">Real labs • Gemini-ready • API-backed</div></aside><main class="main"><div class="topbar"><div class="crumb">NEXUS / '+state.page.toUpperCase()+'</div><div class="profile"><div class="avatar">E</div><div><b>Operator</b><div class="muted">Level '+levelFromXp(state.xp)+'</div></div></div></div><div id="view">'+page()+'</div></main></div>';
}
function dashboard(){
 return '<div class="hero"><section class="card hero-card"><div class="eyebrow">CYBER COMMAND CENTER</div><div class="title">Learn. Investigate.<br>Break the case.</div><div class="sub">NEXUS combines structured learning, real local vulnerable labs, an isolated practice terminal, CTF missions, toolkit modules and Gemini AI tutoring.</div><div class="actions">'+cardButton("Learn →","learn",true)+cardButton("Launch Real Labs","labs")+cardButton("Ask Gemini","ai")+'</div></section><section class="card section"><div class="section-head"><h2>⚡ Operator status</h2><span class="tag">ONLINE</span></div><div class="notice">Recommended path: <b>Web Security → Authentication</b></div>'+[["Linux",84],["Web Security",72],["Networking",61],["Forensics",48]].map(s=>'<div class="skill"><div class="skill-row"><span>'+s[0]+'</span><b>'+s[1]+'%</b></div><div class="progress"><i style="width:'+s[1]+'%"></i></div></div>').join("")+'</section></div><div class="stats">'+[["XP",state.xp.toLocaleString()],["LEVEL",state.level],["CASES SOLVED",state.solved],["STREAK",state.streak+" days"]].map(s=>'<div class="card stat"><div class="k">'+s[0]+'</div><div class="v">'+s[1]+'</div></div>').join("")+'</div><div class="layout"><section class="card section"><div class="section-head"><h2>🎯 Active operations</h2><span class="muted">3 available</span></div>'+missions.map((m,i)=>'<div class="mission"><div><span class="tag">'+m[1]+'</span><h3>'+m[0]+'</h3><div class="muted">'+m[2]+'</div></div>'+cardButton("Open","missions",i===0)+'</div>').join("")+'</section><section class="card section"><div class="section-head"><h2>🤖 Gemini AI</h2><span class="tag">API</span></div><p class="muted">Tutor, hints, explanations and learning guidance through your NEXUS backend.</p>'+cardButton("Open Gemini Tutor","ai",true)+'</section></div>';
}
function learn(){
 return '<div class="layout"><section class="card section"><div class="section-head"><div><h2>🎓 Learn</h2><div class="muted">Learn → practice → prove it.</div></div><span class="tag">'+courses.length+' tracks</span></div>'+courses.map((c,i)=>'<div class="mission"><div><div style="font-size:24px">'+c[0]+'</div><span class="tag">'+c[3]+'</span><h3>'+String(i+1).padStart(2,"0")+' • '+c[1]+'</h3><div class="muted">'+c[2]+' • Progress '+c[4]+'</div><div class="progress" style="margin-top:9px"><i style="width:'+c[4]+'"></i></div></div><button class="btn" data-course="'+i+'">Open</button></div>').join("")+'</section><section class="card section"><div class="section-head"><h2>🧠 Learning loop</h2></div><div class="notice">Every track is designed to connect theory to an authorized practice environment.</div><div class="mission"><div><h3>1. Lesson</h3><div class="muted">Concepts with examples and notes.</div></div></div><div class="mission"><div><h3>2. Interactive check</h3><div class="muted">Questions, mini puzzles and command exercises.</div></div></div><div class="mission"><div><h3>3. Real lab</h3><div class="muted">Launch Juice Shop, WebGoat or DVWA locally.</div></div></div><div class="mission"><div><h3>4. Gemini coach</h3><div class="muted">Ask for hints or explanations without exposing your API key.</div></div></div></section></div>';
}
function courseView(i){
 const c=courses[i]||courses[0];
 return '<section class="card challenge"><div class="eyebrow">LEARN / '+c[1].toUpperCase()+'</div><h1>'+c[1]+'</h1><p class="sub">'+c[3]+'</p><div class="layout"><div><div class="notice">Progress: <b>'+c[4]+'</b></div><h2 style="margin-top:20px">Module roadmap</h2>'+["Core concepts","Interactive examples","Knowledge check","Lab preparation","Hands-on practice","Review & assessment"].map((x,n)=>'<div class="mission"><div><h3>'+String(n+1).padStart(2,"0")+' • '+x+'</h3><div class="muted">Ready to expand into the full course content.</div></div><span class="tag">'+(n<2?"OPEN":"NEXT")+'</span></div>').join("")+'</div><div><div class="card section"><h2>🤖 Gemini tutor</h2><p class="muted">Ask about this track.</p><button class="btn primary" data-page="ai">Ask Gemini</button></div><div class="card section" style="margin-top:12px"><h2>🧪 Practice</h2><p class="muted">Jump into the local lab collection.</p><button class="btn" data-page="labs">Open Real Labs</button></div></div></div></section>';
}
function missionsPage(){return '<div class="layout"><section class="card section"><div class="section-head"><div><h2>🎯 Mission Control</h2><div class="muted">Fictional, sandboxed challenges.</div></div></div>'+missions.map((m,i)=>'<div class="mission"><div><span class="tag">'+m[1]+'</span><h3>'+m[0]+'</h3><div class="muted">'+m[2]+'</div></div><button class="btn '+(i===0?"primary":"")+'" data-challenge="'+i+'">'+(i===0?"Launch":"Preview")+'</button></div>').join("")+'</section><section class="card section"><h2>🧠 Case file</h2><p class="muted">Use evidence, not guesswork.</p><div class="notice">The first case is fully interactive in this MVP.</div></section></div>'}
function labsPage(){return '<div class="layout"><section class="card section"><div class="section-head"><div><h2>🧪 Real Labs</h2><div class="muted">Actual deliberately vulnerable training applications running locally.</div></div><span class="tag">DOCKER</span></div><div class="notice">Run <code>docker compose up -d</code> from the repo. NEXUS binds these targets to localhost by default.</div>'+labs.map(l=>'<div class="mission"><div><div style="font-size:24px">'+l[0]+'</div><span class="tag">'+l[2]+'</span><h3>'+l[1]+'</h3><div class="muted">'+l[3]+'</div></div><a class="btn primary" href="'+l[3]+'" target="_blank" rel="noopener">Launch ↗</a></div>').join("")+'</section><section class="card section"><div class="section-head"><h2>🌍 External platforms</h2><span class="muted">Provider-owned</span></div>'+external.map(x=>'<div class="mission"><div><h3>'+x[0]+'</h3><div class="muted">NEXUS links to the provider rather than mirroring proprietary course/lab files.</div></div><a class="btn" href="'+x[1]+'" target="_blank" rel="noopener">Visit ↗</a></div>').join("")+'</section></div>'}
function terminal(){return '<section class="card section"><div class="section-head"><div><h2>💻 NEXUS Terminal</h2><div class="muted">Simulated filesystem — your machine is untouched.</div></div></div><div id="console" class="console">$ whoami\nnexus\n$ ls\nlogs  evidence  tools  secrets\n$ _</div><div class="command-row"><input id="cmd" placeholder="Try: help, ls, cat logs/access.log"><button class="btn primary" id="run">Run</button></div></section>'}
function toolsPage(){return '<section class="card section"><div class="section-head"><div><h2>🧰 Toolkit</h2><div class="muted">Safe local analysis utilities.</div></div></div><div class="tool-grid">'+tools.map(t=>'<div class="tool" data-tool="'+t[1]+'"><div style="font-size:26px">'+t[0]+'</div><strong>'+t[1]+'</strong><span class="muted">Launch</span></div>').join("")+'</div><div id="toolOut" style="margin-top:15px"></div></section>'}
function challenge(){return '<section class="card challenge"><div class="eyebrow">MISSION 01 / THE STOLEN SERVER</div><h1>Identify the compromised account.</h1><p class="sub">A fictional ACME server reports failed logins followed by a successful login from 192.168.1.44.</p><div class="layout"><div><div class="console">[03:41:52] LOGIN_FAIL user=ops source=192.168.1.44\n[03:42:03] LOGIN_FAIL user=admin source=192.168.1.44\n[03:42:17] LOGIN_SUCCESS user=admin source=192.168.1.44\n[03:42:19] SESSION_OPEN user=admin\n[03:43:01] backup.zip accessed</div></div><div><p class="muted">Which account was compromised?</p><button class="btn choice" data-answer="ops">ops</button><button class="btn choice" data-answer="admin">admin</button><button class="btn choice" data-answer="backup">backup</button><div id="result" style="margin-top:12px"></div></div></div></section>'}
function ctf(){return '<section class="card challenge"><div class="eyebrow">🚩 DAILY CTF</div><h1>Broken Authentication</h1><p class="sub">Use the mission engine, collect the flag, and earn XP.</p><div class="notice">Flag format: <code>NEXUS{...}</code></div><div class="actions"><button class="btn primary" data-challenge="0">Start Challenge</button></div></section>'}
function aiPage(){return '<section class="card section"><div class="section-head"><div><h2>🤖 Gemini Tutor</h2><div class="muted">Your NEXUS backend talks to Gemini — the browser never stores your key.</div></div><span id="aiStatus" class="tag">CHECKING</span></div><div class="notice">Ask for explanations, hints, study plans or help understanding output from your authorized local labs.</div><div id="chat" class="console" style="min-height:260px;margin-top:14px">NEXUS AI ready.\n</div><div class="command-row"><input id="aiInput" placeholder="Ask Gemini anything about the lesson or lab..."><button class="btn primary" id="aiRun">Send</button></div></section>'}
function page(){switch(state.page){case"learn":return learn();case"course":return courseView(state.course||0);case"missions":return missionsPage();case"labs":return labsPage();case"terminal":return terminal();case"tools":return toolsPage();case"ctf":return ctf();case"challenge":return challenge();case"ai":return aiPage();default:return dashboard()}}
async function aiSend(){
 const input=document.getElementById("aiInput"),chat=document.getElementById("chat"),msg=input.value.trim();
 if(!msg)return;
 chat.textContent+="\nYou: "+msg+"\nGemini: thinking...";input.value="";
 try{
   const r=await fetch("/api/ai/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:msg,context:"NEXUS cybersecurity learning platform. User is using authorized local training labs."})});
   const data=await r.json();
   chat.textContent=chat.textContent.replace(/Gemini: thinking\.\.\.$/,"Gemini: "+(data.text||data.error||"No response."));
 }catch(e){chat.textContent=chat.textContent.replace(/Gemini: thinking\.\.\.$/,"Gemini: Backend unavailable. Start NEXUS with npm start.");}
}
function bind(){
 document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});
 document.querySelectorAll("[data-course]").forEach(b=>b.onclick=()=>{state.course=Number(b.dataset.course);state.page="course";render()});
 document.querySelectorAll("[data-challenge]").forEach(b=>b.onclick=()=>{state.page="challenge";render()});
 document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{state.page="tools";render();document.getElementById("toolOut").innerHTML='<div class="notice">Selected: <b>'+esc(b.dataset.tool)+'</b>. This interface is ready for its isolated analysis engine.</div>'});
 if(state.page==="challenge")document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{const r=document.getElementById("result");if(b.dataset.answer==="admin"){r.innerHTML='<div class="notice" style="border-color:var(--green)">✅ Correct — the successful authenticated session is admin. +750 XP.</div>';if(!state.done){state.done=true;state.xp+=750;state.solved++;state.streak=Math.max(1,state.streak);save();setTimeout(render,650)}}else r.innerHTML='<div class="notice" style="border-color:var(--red)">❌ Follow the successful LOGIN_SUCCESS event.</div>'});
 if(state.page==="terminal"){const run=()=>{const i=document.getElementById("cmd"),c=document.getElementById("console"),cmd=i.value.trim();const out={help:"Commands: help, ls, cat logs/access.log, cat evidence/brief.txt, clear",ls:"logs  evidence  tools  secrets","cat logs/access.log":"03:41:52 FAIL ops\n03:42:03 FAIL admin\n03:42:17 SUCCESS admin\n03:43:01 backup.zip accessed","cat evidence/brief.txt":"ACME breach simulation. Correlate login activity with file access.",clear:""}[cmd]??"command not found";c.textContent=cmd==="clear"?"":c.textContent+"\n$ "+cmd+"\n"+out+"\n$ _";i.value="";i.focus()};document.getElementById("run").onclick=run;document.getElementById("cmd").onkeydown=e=>{if(e.key==="Enter")run()}};
 if(state.page==="ai"){fetch("/api/health").then(r=>r.json()).then(x=>{document.getElementById("aiStatus").textContent=x.geminiConfigured?"GEMINI ONLINE":"ADD API KEY"}).catch(()=>{document.getElementById("aiStatus").textContent="BACKEND OFFLINE"});document.getElementById("aiRun").onclick=aiSend;document.getElementById("aiInput").onkeydown=e=>{if(e.key==="Enter")aiSend()}}
}
function render(){document.getElementById("app").innerHTML=shell();bind()}render();
